### ISSUE TITLE
Give user feedback about invalid metrics files

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#1]
As a user 
I want to get a warning if the file to be parsed contains invalid data:
- If the file to be processed contains invalid data (e.g. when the file was not preprocessed)
- If a request id for a single record occurs twice (this is an indicator that files of multiple servers have been merged
- If the file is empty

**Comment by nbrass** [comment]
If loading multiple files the file parsing should not be terminated while errors occur.

**Comment by Florian-W** [comment]
User feedback was added, but a new problem occured: When the user closes the "Load Scenario" dialog the "ParsingAllFilesHasFinishedEvent" is activated and therefore the "Parsing of all files has finished" dialog appears, although no file was processed.

**Comment by skliche** [comment]
Is this resolved now?

**Comment by Florian-W** [comment]
Yes it is, user feedback now only appears when an invalid file was selected and also, only the name of the recently selected invalid file is displayed (e.g. if the user had selected invalid files in a previous file dialog - only the most recent invalid files are shown now).
