### ISSUE TITLE
be able to parse raw SystemOut log

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#12]
As a user
I want to be able to parse raw SystemOut.log files and not rely on preprocessing using grep.

However this is an add-on to the engine, since preprocessing has better performance and also increases visibility of the request metrics.

The engine should detect if the file is preprocessed or not.

**Comment by skliche** [comment]
Throw an event when the engine switched between parsing modes.

**Comment by nbrass** [comment]
Add another regular expression for parsing raw SystemOut files. Engine should switch between modes (raw vs grepped) and throw an event via event framework.
