### ISSUE TITLE
Unable to parse aggregated metrics file that is based on a single SystemOut.log

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#21]
When I use grep to transform a single SystemOut.log file to a metrics file using the command `grep PmiRmArmWrapp SystemOut.log > metrics.txt` the command grep omits the source file name and the entries in the metrics.txt file look like `[10/19/15 18:03:39:649 CEST] 0000011b PmiRmArmWrapp I   PMRM0003I:  parent:ver=1,ip=14.108.96.122,time=1444516035250,pid=4836,reqid=46716,event=1 - current:ver=1,ip=14.108.96.122,time=1444516035250,pid=4836,reqid=46720,event=1 type=JDBC detail=javax.resource.spi.ManagedConnection.cleanup() elapsed=0`

The parser wont recognize the event because the `SystemOut_20151019.log:[` prefix is missing. 

The parser should be able to work with that kind of metrics files aswell.

**Comment by Florian-W** [comment]
Issue was solved by adding the -H variable to the grep command, so that it looks like the following:
grep -H "PMR0003I" SystemOut*.log > metrics.txt
A description how to use the grep command for preprocessing log files was added to the Wiki.

**Comment by skliche** [comment]
Sounds good! Maybe you add the description why exactly "-H" is required and you can also link to this bug.
