### ISSUE TITLE
User feedback during file parsing

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#4]
As a user
I want to get feedback from the GUI while the data files are being parsed

**Comment by skliche** [comment]
Use the observer framework to notify the GUI of the status of the parsing

**Comment by nbrass** [comment]
Feedback via progress bar in percent (two bars for total parsing and actual file parsing). Calculating via whole number of lines of all files to be parsed. Show current file that is parsed in progress bar window.

**Comment by Florian-W** [comment]
A new class will be provided for displaying the JDialog with its two JProgressBars. 
The method buildProgressBars, which does the UI, will be invoked by the RequestMetricsGui.
The RequestMetricsGui will also check-in and check-out the ProgressBar class as an observer of the RmProcessor.
The progress bar dialog opens when the user has selected files for processing. It closes automatically with the "ParsingAllFilesHasFinishedEvent". 
The user can close the dialog while it's processing, which will cause the processor to stop (e.g. if he wants to select other files).

The progress bar dialog will look like this:
![wireframe progressbar2](https://cloud.githubusercontent.com/assets/13657128/10936663/53c72134-82ee-11e5-82e2-81eff0fec9ff.jpg)

**Comment by Florian-W** [comment]
The progress bars were implemented, showing the progress in parsing the files. The dialog also closes automatically after all files are processed.
2 issues persist:
- the processor does not stop processing when the progress bar dialog is closed
- the window is not a modal window, which means that a user can not click the parent window while the progress bar dialog is shown
